  <?php

  /**
  * @file
  * Contains the durhamtech_colleague_migrate module.
  *
  * Currently this only works for select list widgets.
  * @TODO Modify this to work for other widget types.
  */

  /**
  * Implements hook_form_alter().
  */
  function durhamtech_colleague_migrate_form_alter(&$form, $form_state, $form_id) {
    if ($form['#id'] == 'views-exposed-form-course-search-page-1') {
      unset($form['field_location']['#options']['internet']);
    }
  }

  /**
   * Add class data to courses
   */
  function classCourse() {
    $connection = \Drupal::database();
    $courseStorage = \Drupal::entityTypeManager()->getStorage('taxonomy_term');
    $courses = \Drupal::entityQuery('taxonomy_term')
      ->condition('vid', 'course')
      ->execute();

    $visibleLocations = [
      'che',
      'dsn',
      'main_campus',
      'ndc',
      'occ',
      'rtp',
    ];

    foreach ($courses as $course) {
      $courseTerm = $courseStorage->load($course);
      $query = $connection->select('node__field_course', 'nfc');
      $query->addJoin('left', 'node__field_location', 'nfl', 'nfc.entity_id = nfl.entity_id');
      $query->addField('nfc', 'entity_id');
      $query->addField('nfl', 'field_location_value');
      $query->condition('nfc.bundle', 'class', '=');
      $query->condition('nfc.field_course_target_id', $course, '=');
      $classes = $query->execute()->fetchAll();
      if (!empty($classes)) {
        $locations = array_unique(array_column($classes, 'field_location_value'));
        foreach ($locations as $key=>$location) {
          if(!in_array($location, $visibleLocations)) {
            $locations[$key] = 'other';
          }
        }
        $locations = array_unique($locations);
        $courseTerm->set('field_class_count', sizeof($classes));
        $courseTerm->set('field_location', $locations);
        $courseTerm->save();
      } else {
        $courseTerm->set('field_class_count', 0);
        $courseTerm->set('field_location', []);
      }
    }
  }
