module:
  addtoany: 0
  admin_toolbar: 0
  admin_toolbar_links_access_filter: 0
  admin_toolbar_tools: 0
  automated_cron: 0
  better_exposed_filters: 0
  blazy: 0
  block: 0
  block_content: 0
  breakpoint: 0
  ckeditor: 0
  ckeditor_tabletoolstoolbar: 0
  ckeditor_youtube: 0
  color: 0
  colorbox: 0
  comment: 0
  config: 0
  contact: 0
  contextual: 0
  ctools: 0
  ctools_block: 0
  datetime: 0
  datetime_range: 0
  dblog: 0
  devel: 0
  durhamtech_colleague_migrate: 0
  dynamic_page_cache: 0
  editor: 0
  editor_advanced_link: 0
  entity: 0
  entity_browser: 0
  entity_browser_entity_form: 0
  entity_reference_revisions: 0
  facets: 0
  field: 0
  field_defaults: 0
  field_ui: 0
  file: 0
  filter: 0
  fitvids: 0
  fontawesome: 0
  help: 0
  history: 0
  image: 0
  inline_entity_form: 0
  kint: 0
  layout_discovery: 0
  link: 0
  media_entity: 0
  media_entity_image: 0
  menu_block: 0
  menu_ui: 0
  migrate: 0
  migrate_plus: 0
  migrate_source_csv: 0
  migrate_tools: 0
  node: 0
  options: 0
  page_cache: 0
  panelizer: 0
  panels: 0
  panels_ipe: 0
  path: 0
  quickedit: 0
  rdf: 0
  search_api: 0
  search_api_db: 0
  search_api_views_taxonomy: 0
  shortcut: 0
  slick: 0
  slick_ui: 0
  slick_views: 0
  system: 0
  taxonomy: 0
  text: 0
  token: 0
  toolbar: 0
  tour: 0
  twig_tweak: 0
  update: 0
  user: 0
  video_embed_field: 0
  views_ui: 0
  menu_link_content: 1
  pathauto: 1
  xmlsitemap: 1
  views: 10
  paragraphs: 11
  standard: 1000
theme:
  stable: 0
  classy: 0
  bartik: 0
  seven: 0
  bootstrap: 0
  durhamtech: 0
profile: standard
_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
